version: '3'
services:
  app:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh 
    environment:
      APP_ENV:
    volumes:
      - .:/app
